### ISSUE TITLE
Implement browser history

### ISSUE THREAD

**Issue by cwhitey** [benbowes/redux-saga-api-example#1]
I want to be able to search for a bunch of different gifs, then go back to the ones I liked best with maximum efficiency! 

<img src="https://media1.giphy.com/media/l0MYxef0mpdcnQnvi/giphy.gif" width="100%" />

**Comment by benbowes** [comment]
Hi @cwhitey, are you talking about deep-linking/routing ?

Or a "save favourites" functionality?

I have had a play with routing (WIP) https://gif-driven-development.herokuapp.com/search/monkey

**Comment by benbowes** [comment]
Complete

**Comment by cwhitey** [comment]
💯
